absoluteurl: http://AIMS-Ghana.github.io
baseurl: '/cams'
repourl: 'https://raw.githubusercontent.com/AIMS-Ghana/cams/gh-pages/_includes/'
markdown: kramdown
encoding: utf-8
css:
  active: "active"
aimsghurl: "http://www.aims.edu.gh/"
render:
  - sessions
  - practice
  - projects
collections:
  warmups:
    output: true
    permalink: warmup/:name/
  topics:
    output: true
    permalink: :name/
  practice:
    output: true
    permalink: :name/practice/
  projects:
    output: true
    permalink: :name/project/
  sessions:
    output: true
    permalink: :name/session/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "section"
  -
    scope:
      type: "topics"
    values:
      area: "topic"
  -
    scope:
      type: "sessions"
    values:
      area: "session"
  -
    scope:
      type: "projects"
    values:
      area: "project"
  -
    scope:
      type: "practice"
    values:
      area: "practice"
exclude:
 - '*.sh'
 - Gemfile
 - README.md
 - LICENSE
