absoluteurl: http://AIMS-Ghana.github.io
baseurl: '/seams'
repourl: 'https://raw.githubusercontent.com/AIMS-Ghana/seam/gh-pages/_includes/'
markdown: kramdown
encoding: utf-8
css:
  active: "active"
collections:
  warmups:
    output: true
    permalink: /warmup/:name/
  topics:
    output: true
    permalink: /topic/:name/
  practice:
    output: true
    permalink: /practice/:name/
  projects:
    output: true
    permalink: /project/:name/
  sessions:
    output: true
    permalink: /session/:name/
defaults:
  -
    scope:
      path: ""
    values:
      layout: "section"
exclude:
 - run.sh
 - Gemfile
 - README.md
 - LICENSE
